// <auto-generated />
using System;
using FiledWebApi.Models.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FiledWebApi.Migrations
{
    [DbContext(typeof(PaymentsContext))]
    [Migration("20210314095708_EFCoreCodeFirstSample.Models.PaymentStatusesContextSeed")]
    partial class EFCoreCodeFirstSampleModelsPaymentStatusesContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FiledWebApi.Models.DbModels.PaymentStatuses", b =>
                {
                    b.Property<int>("PaymentStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentStatusID");

                    b.ToTable("PaymentStatuses");

                    b.HasData(
                        new
                        {
                            PaymentStatusID = 1,
                            CreatedDate = new DateTime(2021, 3, 14, 14, 57, 8, 60, DateTimeKind.Local).AddTicks(8817),
                            IsActive = true,
                            Name = "pending"
                        },
                        new
                        {
                            PaymentStatusID = 2,
                            CreatedDate = new DateTime(2021, 3, 14, 14, 57, 8, 62, DateTimeKind.Local).AddTicks(3792),
                            IsActive = true,
                            Name = "processed"
                        },
                        new
                        {
                            PaymentStatusID = 3,
                            CreatedDate = new DateTime(2021, 3, 14, 14, 57, 8, 62, DateTimeKind.Local).AddTicks(3815),
                            IsActive = true,
                            Name = "failed"
                        });
                });

            modelBuilder.Entity("FiledWebApi.Models.DbModels.Payments", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentStatusID")
                        .HasColumnType("int");

                    b.Property<int>("RetryCounts")
                        .HasColumnType("int");

                    b.Property<string>("SecurityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentID");

                    b.HasIndex("PaymentStatusID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FiledWebApi.Models.DbModels.Payments", b =>
                {
                    b.HasOne("FiledWebApi.Models.DbModels.PaymentStatuses", "PaymentStatuses")
                        .WithMany()
                        .HasForeignKey("PaymentStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
